### ISSUE TITLE
In the AS3 settings `ClodFront distribution ID` label is misspelled. 

### ISSUE THREAD

**Issue by a-am** [craftcms/aws-s3#1]
In the AS3 settings `ClodFront distribution ID` label is misspelled. 
![screen shot 2017-01-31 at 1 10 59 pm](https://cloud.githubusercontent.com/assets/976370/22482598/e3804af2-e7b6-11e6-94ed-979b50ae9fa1.png)

**Comment by takobell** [comment]
Fixed in release 1.0.1.
