### ISSUE TITLE
IAM Role support

### ISSUE THREAD

**Issue by cdenneen** [craftcms/aws-s3#105]
### Description

Support IAM Role as alternative to Access and Secret Keys.
Current documentation specifies Keys are necessary but is role an option and if so do you leave the key fields blank?

**Comment by andris-sevcenko** [comment]
I'm not sure I follow. How would you authorize the user for the IAM role if not by providing the keys?

**Comment by sjoerdklaveringakpn** [comment]
Hi all, I would second this request. 

As part of our architecture, we use IAM roles to give access to certain resources. Only for our sites using Craft we need to add IAM users to pass the credentials, even though the container the CMS runs in already has access to the relevant buckets by role. So basically, you could make the key / secret key optional and it will work.

Feel free to reach out to me for more information.

**Comment by andris-sevcenko** [comment]
@sjoerdklaveringakpn I'm confused. You already can skip the key ID and secret key, if the machine has access already.

**Comment by sjoerdklaveringakpn** [comment]
Sorry for the confusion people, I don't have access to the application as I do the cloud (infra) architecture & I misinterpreted the developer's statement that the container would not work without these credentials.

**Comment by angrybrad** [comment]
No worries... going to go ahead and close this out, then.
