### ISSUE TITLE
Typo in S3 URL builder

### ISSUE THREAD

**Issue by aeu** [craftcms/aws-s3#109]
### Description
There is a typo in the s3 URL builder function in editVolume.js, where .com is omitted after amazonaws.  This causes the URL that is stored in the site to be broken.

### Steps to reproduce

1. Create an AWS Volume
2. Upload an image
3. Try to preview it, link will broken.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by aeu** [comment]
Fix is here:

https://github.com/craftcms/aws-s3/pull/110

**Comment by andris-sevcenko** [comment]
Thanks, all merged!
