### ISSUE TITLE
Craft Unable to Receive Credentials from Instance Metadata in AWS ECS

### ISSUE THREAD

**Issue by yhakbar** [craftcms/aws-s3#112]
### Description

When configuring the S3 plugin using the instructions provided and the permissions recommended in the README.md on a Fargate ECS task, configuration of a volume failed due to an inability to receive credentials from instance metadata.

<img width="776" alt="Screen Shot 2021-03-25 at 17 46 15" src="https://user-images.githubusercontent.com/11247449/112549436-2fb50200-8d94-11eb-87ee-c33b7d14c80a.png">

I configured the plugin settings such that there was no access key id or secret access key, hoping that the IAM role associated with the ECS task would be assumed through instance metadata.

### Steps to reproduce

1. Create S3 bucket.
2. Create IAM role with permissions listed on the README.md of this repo to connect to that bucket.
3. Spin up a Craft CMS ECS task with the IAM role mentioned in step 2 associated with it.
4. Attempt to hit "Refresh" on the bucket selection page of an asset volume settings page to get a list of S3 buckets or attempt to upload to a manually configured S3 bucket through the assets page.

### Additional info

- Craft version: 3.6.10
- PHP version: 7.4
- Plugins & versions:
  - aws/aws-sdk-php: 3.175
  - craftcms/aws-s3: 1.2.11

**Comment by andris-sevcenko** [comment]
This plugin does not manage the credentials in any way besides using them if they are provided when creating the S3 client.

If no key ID and secret are provided, the plugin assumes that this is on an ECS instance and creates the S3 client without any credentials and then AWS takes care of that further down the line.

**Comment by yhakbar** [comment]
Thanks for your reply @andris-sevcenko . Just for your awareness, I'm talking to @jasonmccallister on a support ticket trying to resolve this issue as well.

I think there's still a chance that this is a valid plugin issue, but I'm not sure, as I'm able to communicate with instance metadata on the Fargate task that I'm running in ECS, but for some reason I can't connect to it correctly from within Craft.

If there's some way in which the instance metadata endpoint is configurable on the PHP SDK configurations, it's possible that this is the root cause of the failure to connect.
