### ISSUE TITLE
Error executing "GetSessionToken" on "https://sts.amazonaws.com"; AWS HTTP error: Client error: `POST https://sts.amazonaws.com` resulted in a `403 Forbidden` response

### ISSUE THREAD

**Issue by peimansh** [craftcms/aws-s3#114]
### Description
Trying to phase out Volumes.php from our installation, so I removed the file, Configured everything via Control Panel in local dev, committed Project Config changes, and am trying to push changes to staging and I get this error.

### Steps to reproduce

1. Remove Volumes.php file
2. Configure Volumes from CP
3. Commit changes and push to another environment

### Additional info

- Craft version: 3.6.12
- PHP version: 7.4
- Database driver & version: PostgreSQL 11
- Plugins & versions: aws-s3: "1.2.11"

**Comment by peimansh** [comment]
Well, Not sure if related or not, I was trying to update and Apply new changes at the same time which would have caused the issue, if doing it separately, I'm not getting the error.

**Comment by andris-sevcenko** [comment]
That's a strange one. Perhaps it was caught in some limbo place where it couldn't find the credentials because you were doing those things at the same time. Unlikely, but I can't currently imagine how it could have happened.

Closing this one out, if the error is gone!

**Comment by peimansh** [comment]
To be more specific, the problem happens when you try to phase out volumes.php from the installation.
So I remove volumes.php, configure everything in CP, commit everything, push to new environment, and then the Error is shown.
If I include volumes.php in the first deploy, the error is not shown, but if I don't include volumes.php this is the error I get.
