### ISSUE TITLE
Can't remove Cloudfront Query Strings from image URL's

### ISSUE THREAD

**Issue by riusi88** [craftcms/aws-s3#115]
### Description
I have images setup in an S3 bucket, with a Cloudfront Distribution. Images are loading as expected, and are being served off of the Cloudfront URL. However, the image URL's include unnecessary URL parameters such as `&focal=none&tmtime=20210315052434`. 

**Example:**

`https://d31wn8gmdcz28h.cloudfront.net/block_images/_pageHeader/AdobeStock_193312500-Converted.png?mtime=20210315052434&focal=none&tmtime=20210505140954`

I'm not sure how to prevent this from happening, and ideally I'd have a clean image URL that would look like this:
`https://d31wn8gmdcz28h.cloudfront.net/block_images/_pageHeader/AdobeStock_193312500-Converted.png`

I've made sure that the Cache Behaviour settings for the Cloudfront Distribution are using Policies that explicitly state that Origin request contents, and Cache key contents such as Headers, Cookies and Query Strings are set to "None". Yet the image URL's continue to include the query strings when they are loaded into my twig templates. 
   
For my AWS and Cloudfront settings I followed these configuration instructions from this nystudio107 article:
`https://nystudio107.com/blog/using-aws-s3-buckets-cloudfront-distribution-with-craft-cms`

The only difference in my own Asset Volume settings is that "Add subfolder to URL" is set to True, which wasn't an option at the time nystudio107 published the article.

The reason I'd like to remove these Query Strings is because I'm trying to load `webp` versions of images via these instructions using the Image Optimization plugin:
`https://nystudio107.com/docs/image-optimize/Using.html#image-variants`

If query strings exist in the image url's, I won't be able to append `webp` to my images properly like so:
`entry.someAsset.one().getUrl('someTransform') ~ '.webp'` since the query string will be between the `.png` or `.jpg` and `.webp`.

Hoping you'll be able to help me troubleshoot this issue. Let me know if you need more information. 

### Additional info

- Craft version: 3.6.12
- PHP version: 7.3.27
- Plugins & versions: Amazon S3 1.2.11

**Comment by andris-sevcenko** [comment]
The query parameters are added for cache-busting, if your volume has Expires header set up. This is because those headers are eventually forwarded to the browsers. Unless Craft changes the URL based on the actual image used, this can lead to a very undesirable situation of stale images being cached in the browser for days, depending on the setting.

In your case something like `entry.someAsset.one().getUrl('someTransform')|replace("/\.(png|jpg)/", ".$1.webp")` would probably work, too.

Let me know hot it goes!

**Comment by riusi88** [comment]
Hey @andris-sevcenko thanks for the quick response, and I certainly want to prevent any stale images so I suppose my hands are tied. 

Good to know I was going down the right path with a fix as I had written something similar: `entry.someAsset.one().getUrl('someTransform')|split('?')[0] ~ '.webp'`

Both your code and mine work to remove the unwanted query strings, and thank you for the help!

**Comment by andris-sevcenko** [comment]
> Both your code and mine work to remove the unwanted query strings, and thank you for the help!

The code I posted should preserve the query string, so you get the best of both worlds!

**Comment by riusi88** [comment]
Excellent, thanks again for the recommendation!
