### ISSUE TITLE
Migration not needed?

### ISSUE THREAD

**Issue by ostark** [craftcms/aws-s3#12]
I try to understand what's happening in the Install migration. 
Is `volumes.type = 'craft\volumes\AwsS3'` a legacy thing? I can't find any reference to that class.

https://github.com/craftcms/aws-s3/blob/master/src/migrations/Install.php#L62

Similar things happen in Rackspace and GoogleCloud plugin.

**Comment by andris-sevcenko** [comment]
Craft 2 had AWS, Google Cloud and Rackspace support were built-in. That migration is in place so that any Craft 2 Asset sources would get converted to the appropriate Volume type in Craft 3.

**Comment by takobell** [comment]
For reference:

https://github.com/craftcms/aws-s3
https://github.com/craftcms/google-cloud
https://github.com/craftcms/rackspace

Installable via the plugin store.
