### ISSUE TITLE
Wrong check for non existing environment variables

### ISSUE THREAD

**Issue by fleaz** [craftcms/aws-s3#120]
Hey,

I discovered a rather severe bug in the latest version (1.2.12):
You use `parseEnv()` to get the value of these two variables in this line:
https://github.com/craftcms/aws-s3/blob/a5a20c01e4f6273b48c8057651e17d10ee484e85/src/Volume.php#L434

When the variable is empty this will work, but in the case these variables doesn't exist the function parseEnv() will return the name of the variable itself to differentiate the case from an empty variable (See this line in the Craft source: https://github.com/craftcms/cms/blob/main/src/Craft.php#L93)

This results in the behavior that the plugin will try to use the WebIdentityProvider even though it is not configured and the needed files are not present. This results in the error `Unknown profile: default`
![Bildschirmfoto 2021-07-29 um 09 40 32](https://user-images.githubusercontent.com/2489598/127506834-3db3d0d1-55e1-4788-b7ed-6d6a9deac741.png)

Best regards,
Felix

**Comment by timkelty** [comment]
Thanks @fleaz,
You're right - we're working on a patch for this right away.

Stay tuned!

**Comment by timkelty** [comment]
@fleaz `1.2.13` is out with a fix for this, can you give it a shot?

**Comment by fleaz** [comment]
Perfect! Works like a charm now. Thanks for the fast fix :)
