### ISSUE TITLE
S3 Base URL Generation Using Deprecated URL

### ISSUE THREAD

**Issue by iamderrick** [craftcms/aws-s3#128]
When the plugin automatically tries to generate the base URL for a publically accessible S3 bucket, it uses the old path-style model rather than the new virtual-hosted model. This older URL model does not work with newer S3 buckets. See: https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/

**Comment by timkelty** [comment]
Yeah, as long as it's https by default, prob should go with the virtual-hosted version.
@iamderrick happy to review a PR, otherwise we'll get to it soon.

**Comment by brianjhanson** [comment]
It looks like the plans to deprecate the old path-style have been put on pause somewhat indefinitely. Either way, I've opened a PR to address this.

**Comment by brandonkelly** [comment]
Amazon S3 1.3.1 (Craft 3) and 2.0.2 (Craft 4) are out now, and use the new URL format by default.
