### ISSUE TITLE
Using isNew property to check for newly created model

### ISSUE THREAD

**Issue by sijones-uk** [craftcms/aws-s3#129]
### Description

Since Craft 3.7.5, the `isNew` property [is no longer reliable](https://craftcms.com/knowledge-base/upgrading-to-craft-3-7#detecting-newly-saved-entries) when determining whether the entry is being saved for the first time. It is recommended to use the newly created (as of Craft 3.7.5) `firstSave` property instead.

### Steps to reproduce

1. [Line 45 in the `Plugin` class](https://github.com/craftcms/aws-s3/blob/main/src/Plugin.php#L45) uses the `isNew` property to check if the Asset model is newly created

### Additional info

- Craft CMS version: 3.7.14
- Amazon S3 plugin version: 1.2.15
- PHP version: 7.4.1
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
Amazon S3 | 1.2.15

**Comment by andris-sevcenko** [comment]
I personally have no preference here, but you should know that @timkelty will have an opinion.

Context: https://github.com/craftcms/aws-s3/issues/34

**Comment by andris-sevcenko** [comment]
Sorry for the previous comment, that was intended for a different issue 🤦 

As far as this recommendation goes - it's only needed for element types that support drafts. Since assets don't support drafts (and unlikely will in any foreseeable future), using `isNew` is fine here.
