### ISSUE TITLE
when replacing an asset an error 'doesn't have the original file extension' occurs

### ISSUE THREAD

**Issue by 24HOURSMEDIA** [craftcms/aws-s3#13]
When I want to replace an asset through the 'upload files button' in the S3 volume (with an asset of the same filename),

I get a 'doesn't have the original file extension' message (even though the new asset has).

Then a new asset with a new filename is created.

**Comment by brandonkelly** [comment]
This ended up being a Craft bug that affected all volume types. Fixed via https://github.com/craftcms/cms/commit/65b12c73d284589c854604e1578bbfeac09d7e42.
