### ISSUE TITLE
Missing input fields for Amazon S3 

### ISSUE THREAD

**Issue by JordanMed** [craftcms/aws-s3#133]
### Description
Missing input fields within the amazon S3 asset volume 

I have multiple environments (local host, staging, production) and the fields are missing on my staging environment. 

![Screen Shot 2021-12-01 at 2 27 34 PM](https://user-images.githubusercontent.com/54858742/144292437-31149f87-423e-4a6c-ae0e-c8747dc806e6.png)

This seems to be a problem from craft. 

### Steps to reproduce
No steps. 
1.
2.

### Additional info

- Craft CMS version: 3.7.19.1
- Amazon S3 plugin version: 1.3.0
- PHP version: 7.4.21
- Database driver & version: MySQL 5.7.12
- Plugins & versions:

**Comment by andris-sevcenko** [comment]
Are there any JS errors in your browser's dev console?

**Comment by JordanMed** [comment]
ended up being a JS error as you suspected.
