### ISSUE TITLE
Enormous Loading Times in Craft CMS 4

### ISSUE THREAD

**Issue by thomassausen** [craftcms/aws-s3#139]
### Description
If the plugin is activated, I bareley can use Craft CMS 4 anymore. If I click on Entries or other menu items, enormous load times might happen. 

### Additional info

- Craft CMS version: 4.0.0.1-Beta
- Amazon S3 plugin version: 2.0.0-beta.1
- PHP version: 8.0.15
- Database driver & version: MySQL 8.0.27
- Plugins & versions: Redactor 3.0.0-beta.1 and Seomatic 4.0.0-beta.3

**Comment by andris-sevcenko** [comment]
Thanks, I see how this could have been introduced. We'll talk it over and get a fix out soon!

FWIW, it's not this plugin, it's Craft's issue.

**Comment by thomassausen** [comment]
Ok, thought it might be a problem with this Plugin, because I‘ve got the enormous loading times only if this Plugin is activated. If it‘s active I also can’t see image previews. I Just see the file names.

I made a video about this loading times, just in case. 

But You’re working on a fix and that’s great.
