### ISSUE TITLE
Can't activate plugin after installation

### ISSUE THREAD

**Issue by mcntsh** [craftcms/aws-s3#14]
This might be a an issue for https://github.com/craftcms/cms but after I run `composer require craftcms/aws-s3`, I'm unable to activate the plugin in the control panel. The AWS plugin itself is marked with a check but when I open the plugin to activate it nothing happens.

**Comment by brandonkelly** [comment]
You can finish the installation from Settings → Plugins, per the [installation instructions](https://github.com/craftcms/aws-s3#installation).
