### ISSUE TITLE
AWS credentials cache duration is not being calculated correctly

### ISSUE THREAD

**Issue by Zae** [craftcms/aws-s3#153]
### Description
In v1.3 of the plugin the aws credentials cache duration is not being calculated correctly. The result is always 1 second, which is wrong.

See  #152 for fix

### Repro:
https://3v4l.org/WLBJU

### Additional info

- Craft version: 3.7
- PHP version: 8.1
- Database driver & version:
- Plugins & versions: 1.3

**Comment by Zae** [comment]
V2 has the same bug but in a different file: https://github.com/craftcms/aws-s3/blob/main/src/Fs.php#L466

**Comment by brandonkelly** [comment]
Fixed via #152.

**Comment by justinholtweb** [comment]
I'm still getting this issue on 1.3.2 as of May 23
