### ISSUE TITLE
Incorrect host name generated by plugin?

### ISSUE THREAD

**Issue by vonscriptor** [craftcms/aws-s3#16]
Error message _(shown below)_ is trying to use the following host name:
`'brigade-website.s3.s3-us-west-2.amazonaws.com'`

---

**config/volumes.php**
'url' => ```'url' => 'https://'.getenv('S3_REGION').'.amazonaws.com/'.getenv('S3_BUCKET').'/',```

**/admin/utilities/php-info**
S3_BUCKET= `brigade-website`
S3_REGION= `s3-us-west-2`

**When uploading an image the following error is given:**
`Upload failed. The error message was: “Error executing "ListObjects" on "https://brigade-website.s3.s3-us-west-2.amazonaws.com/?prefix=craftcms_assets%2Fblocks%2Fimage-copy%2F&delimiter=%2F&encoding-type=url"; AWS HTTP error: cURL error 51: SSL: no alternative certificate subject name matches target host name 'brigade-website.s3.s3-us-west-2.amazonaws.com' (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)”`

**Comment by angrybrad** [comment]
cURL 51 error usually means that (in this case) AWS is using an SNI SSL certificate, but your local OpenSSL setup doesn't know how to process that.

Technically there are 3 things a server needs to recognize SNI SSL certs:

1) Using a version of cURL that supports it, at least 7.18.1 (8 years old: https://curl.haxx.se/changes.html)

2) Using a version of cURL compiled against a library that supports SNI, e.g. OpenSSL 0.9.8j (depending on the compilation options some older versions. 7 years old: https://www.openssl.org/news/changelog.html)

3) Using TLS 1.0 at least (not SSLv3)

I'd start by checking your local requirements against those.

**Comment by valish** [comment]
@angrybrad getting a similar issue during a fresh upgrade to Craft3. 

When attempting to "Update asset indexes" from the CP, it returns this error:
`Error executing "ListObjects" on "https://mywebsite.s3.us.amazonaws.com/?prefix=&encoding-type=url"; AWS HTTP error: cURL error 6: Could not resolve host: mywebsite.s3.us.amazonaws.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

It seems the region is being added to the s3 url, where in fact the correct url is `https://mywebsite.s3.amazonaws.com`. 

Can this be overridden or might you have guidance on how to fix this in the CP? The assets are referenced just fine in the actual templates.

**Comment by andris-sevcenko** [comment]
Can you share your Volume configuration? Is it in line with the changes [here](https://github.com/craftcms/aws-s3/commit/000eb4fbf6a3de868edd6e284f3d181daefde915)?

**Comment by valish** [comment]
oops, I glossed over the config file in the README. I didn't realize it was necessary since it was beneath "Per-Environment Configuration", which I wasn't thinking about yet. Hope these keywords help someone's laziness in the future. Thanks Andris!

**Comment by mannachurch** [comment]
I'm getting the same issue

`Error executing "ListObjects" on "https://hd-sermon-archive.s3.us.amazonaws.com/?prefix=&encoding-type=url"; AWS HTTP error: cURL error 6: Could not resolve host: hd-sermon-archive.s3.us.amazonaws.com`

I don't need different environments set up. The URL should be `https://s3.amazonaws.com/hd-sermon-archive` to access the asset but the plugin is adding a different url. This is what's happening after an upgrade from Craft 2 to Craft 3. Everything works perfectly on Craft 2 but it's Craft 3 where this is happening. I tried updating the base url in the CP and in a volumes.php but it's not working. Anything else I can try?

**Comment by andris-sevcenko** [comment]
What is the URL set to in `volumes.php`? The CP one won't matter, since `volumes.php` just overrides those settings.

**Comment by mannachurch** [comment]
This is what I have in volumes.php I'm only trying to override the url.

`<?php

return [
    'myS3VolumeHandle' => [
        'hasUrls' => true,
        'url' => 'https://s3.amazonaws.com/',
   ],
];`

Do I have it wrong?

**Comment by mannachurch** [comment]
Even if I remove the volumes.php file, enabled `Assets in this volume have public URLs` and enter `https://s3.amazonaws.com/` as the base url, it doesn't change anything. I don't care which method I use, I  just need it to override the default url that Craft is generating.

**Comment by andris-sevcenko** [comment]
Should not be the case. Is this on an install it's possible to get FTP and CP access? If so, can you get in touch over support@craftcms.com?

**Comment by mannachurch** [comment]
Thank you, info has been sent. :)

**Comment by danieltott** [comment]
I was having the same issue - it was trying to "ListObjects" on `//s3.us.amazonaws.com` which doesn't exist. I had to go into mysql and hand-edit the `settings` column for my volumes in the `craft_volumes` table, and change `"region":"US"` to `"region":"us-east-1"`
