### ISSUE TITLE
Error Getting Session Token

### ISSUE THREAD

**Issue by dillonbailey** [craftcms/aws-s3#18]
Hello!

Running into an issue that has been a little difficult to track down. The attached error message appears whenever I try to upload a file via the Admin. I have tried using admin level API Key/Secret so I do not believe it's an IAM permissions issue with S3 as this still results in the error.

<img width="519" alt="screen shot 2018-03-15 at 8 51 07 am" src="https://user-images.githubusercontent.com/1067872/37432886-0fc77cda-282e-11e8-900e-b0bf2afb75bc.png">

##Admin Configuration
<img width="1208" alt="screen shot 2018-03-15 at 8 56 09 am" src="https://user-images.githubusercontent.com/1067872/37433147-df4fea0a-282e-11e8-8ef9-5163fae577cb.png">

``` .env
# The AWS API key with read/write access to S3
S3_API_KEY="xxx"

# The AWS API key secret
S3_SECRET="xxx"

# The name of the S3 bucket
S3_BUCKET="assets.thewellresource.org.au"

# The region the S3 bucket is in
S3_REGION="ap-southeast-2"
```
``` config/volumes.php
<?php

return [
    's3Uploads' => [
        'hasUrls' => true,
        'url' => 'https://'.getenv('S3_BUCKET').'.s3.amazonaws.com/',
        'keyId' => getenv('S3_API_KEY'),
        'secret' => getenv('S3_SECRET'),
        'bucket' => getenv('S3_BUCKET'),
        'region' => getenv('S3_REGION'),
    ],
];
```

**Comment by dillonbailey** [comment]
Quick follow-up...

As soon as I attempted the same configuration from my EC2 instance it worked like a charm. So I do not know if there are any specific issues with this working from a local vagrant box?

**Comment by dillonbailey** [comment]
And...after rebooting vagrant the issue is gone...

Opened and closed in 15 minutes ‼️

**Comment by angrybrad** [comment]
Been waiting all day to us this, so thanks!

https://www.youtube.com/watch?v=p85xwZ_OLX0

**Comment by andris-sevcenko** [comment]
For future reference, you get that error when the system making the call does not have the system clock set correctly.

**Comment by dillonbailey** [comment]
Cheers, I was trying to decipher the meaning of time travel with that error message, but makes perfect sense.
