### ISSUE TITLE
Default Upload Location not taken into account

### ISSUE THREAD

**Issue by davorpeic** [craftcms/aws-s3#19]
Hi,

in field settings creating custom path using {slug} or even simple folder doesn't creates that folder in S3, the image gets uploaded just fine but in the configured bucket. This could be potentially be permissions issue set in S3 policy, but either way, would like to see if someone is using this and can test on their side.

![slug](https://user-images.githubusercontent.com/694091/39066277-1c9132c0-449a-11e8-8837-4c6fd0a890de.jpg)

Version: Craft CMS 3.0.3.1

**Comment by andris-sevcenko** [comment]
This is the same issue as craftcms/cms#2778

Maybe you're looking to use the "Restrict uploads to a single folder" setting?

**Comment by davorpeic** [comment]
Hey @andris-sevcenko yeah, that was it, I remembered I had the same 'issue' with craft2. thanks
