### ISSUE TITLE
Cant create or view volumnes when enabled

### ISSUE THREAD

**Issue by jackmcpickle** [craftcms/aws-s3#2]
Once active - trying to create a volumn `/settings/assets/volumes/new` or view existing `/settings/assets/volumes/1` throws

```
Internal Server Error
An error occurred when rendering a template.
```

stack track on single call - http://pastebin.com/n666PVuQ

**Comment by andris-sevcenko** [comment]
@jackmcpickle have you tried the 1.0.2 release if that fixes things for you?
