### ISSUE TITLE
[Feature Request] Ability to not include the bucket’s subfolder in the public URL when using CloudFront with an origin path

### ISSUE THREAD

**Issue by benface** [craftcms/aws-s3#20]
I have a single S3 bucket for all my sites, with an `assets` directory that contains subdirectories for each site, so it looks like this:

- `https://mybucket.s3.amazonaws.com/assets/site1/asset.png`
- `https://mybucket.s3.amazonaws.com/assets/site2/asset.png`
- etc.

I set up CloudFront on one of the sites, with the following origin settings:

![cloudfront-origin-settings](https://user-images.githubusercontent.com/1059139/39093857-3c948a30-45f4-11e8-9a62-df5edac33f07.png)

As you can see, I have set an "origin path" so that my URLs look like this:

```
https://xxxxxxxxx.cloudfront.net/asset.png
```

instead of this:

```
https://xxxxxxxxx.cloudfront.net/assets/site1/asset.png
```

It works, but the Craft CMS's S3 plugin doesn't seem to support such a configuration. Here are my settings:

![craftcms-s3](https://user-images.githubusercontent.com/1059139/39093928-4e8f3cca-45f5-11e8-8271-d06976a92292.png)

The problem is that I need to set "Subfolder" to the proper path relative to the bucket because that's where I need my assets for that site to be uploaded, but it results in Craft thinking my assets have URLs like this:

```
https://xxxxxxxxx.cloudfront.net/assets/site1/asset.png
```

instead of this:

```
https://xxxxxxxxx.cloudfront.net/asset.png
```

Would it be possible to add an extra setting called "Include subfolder to public URLs" or something like that? It would be enabled by default of course because I realize my use case is a minority, but I still think it should be supported.

Thanks!

**Comment by andris-sevcenko** [comment]
You're right that you're in minority - over the 5 years of Craft, this is the first time I've heard of such need :)

Seeing that it's practically never needed, I'm not sure we'll add it. We'll talk about it, but no promises.

What you can do in meantime is just fork or extend the plugin and override the `craft\awss3\Volume::getRootUrl()` method to remove the subfolder addition to the URL.

**Comment by benface** [comment]
Ok, so what are most people doing then, between creating a separate bucket for each site or creating a subfolder for each site in the same bucket?

Thank you for the workaround. :)

**Comment by andris-sevcenko** [comment]
To me keeping each site in its own bucket (or even several buckets for a site, depending on the site), seems the right approach to me - makes it easier to separate them, if needed. Or, perhaps, keep the hosting costs separated for accounting purposes.

**Comment by benface** [comment]
Thanks @andris-sevcenko, that makes sense. I thought creating a bucket was a lot of hassle but I don't think it is, looking at it now. I think I'll go that route, thank you!
