### ISSUE TITLE
Stop Forcing must-revalidate header

### ISSUE THREAD

**Issue by mattcdavis1** [craftcms/aws-s3#27]
As far as i can tell there is no hook or event short of extending the volume and overriding the `addFileMetadataToConfig` method that will allow me to remove the `must-revalidate` header that is being added to all my S3 uploaded files.

When i run a [Chrome audit](https://goo.gl/RDJrS8) on my site I am getting a "Uses inefficient cache policy" due to the `must-revalidate` header. Please make this option (whether to include `must-revalidate` and ideally any other headers) configurable in a setting somewhere.

**Comment by andris-sevcenko** [comment]
Besides Chrome audit complaining, why is that header a problem?

All it's doing is telling the browser "once the 30 days are up, you MUST get a fresh version".

An event for the metadata is a good idea for a general extensibility, but I'm curious whether there's an actual problematic scenario or not that you're having.

**Comment by mattcdavis1** [comment]
Why does there need to be another reason? I'm sure the audit team had good
reason to add this warning. You may not be fully understanding the
implications of this header.  See this stackoverflow post
<https://stackoverflow.com/questions/18148884/difference-between-no-cache-and-must-revalidate>for
example:


> "The must-revalidate directive ought to be used by servers if and only if
> failure to validate a request on the representation could result in
> incorrect operation, such as a silently unexecuted financial transaction."


A secondary reason though would just be the principle of control - i ought
to be the one determining what headers i do and don't include in my server
responses not the system.

**Comment by mattcdavis1** [comment]
Why does there need to be another reason? I'm sure the audit team had good
reason to add this warning. You may not be fully understanding the
implications of this header.  See [this stackoverflow post](https://stackoverflow.com/questions/18148884/difference-between-no-cache-and-must-revalidate) for example:

> The must-revalidate directive ought to be used by servers if and only if failure to validate a request on the representation could result in incorrect operation, such as a silently unexecuted financial transaction.

A secondary reason though would just be the principle of control - i ought
to be the one determining what headers i do and don't include in my server
responses not the system.

**Comment by andris-sevcenko** [comment]
Better late than never!

The `must-revalidate` header no longer gets added to uploads, as that is, indeed, not exactly suited for this scenario.
