### ISSUE TITLE
Admin settings do not inherit from `.env`

### ISSUE THREAD

**Issue by dillonbailey** [craftcms/aws-s3#28]
**Current Behaviour**
After installing and following the plugin instructions on the README.md, setting up a new volume via the admin forces users to re-enter API Key and Secret (even if these are set in the .env).

**Ideal Behaviour**
If the `S3_API_KEY` and `S3_SECRET` are set in `.env` these should overwrite any settings in the admin panel, otherwise what is the point of storing these values in the `.env`

**Comment by jsunsawyer** [comment]
Agreed! I just implemented the .env/volumes.php solution as documented and was surprised at how useless it was.

Creating multiple s3 volumes is a pain in the asset setup process. I was hoping that this would allow me to pre-populate/override any of the settings defined in my volumes config file.

On that note, it might even be nice to have a settings panel where we could input our s3 settings and then tie them to s3 volumes as needed.

**Comment by brandonkelly** [comment]
This is possible as of v1.1.0.
