### ISSUE TITLE
Use https urls as generated default

### ISSUE THREAD

**Issue by timkelty** [craftcms/aws-s3#34]
By default, it generates a base URL using the virtual-hosted–style url:: http://mybucketname.s3.amazonaws.com/

The default should be https.

Furthermore, by defaulting to the path-based URL, SSL will work no matter what the bucket name is (even if it contains a period "."): https://s3.us-east-1.amazonaws.com/dev.mybucketname/

https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro

**Comment by zuccs** [comment]
If you're using environment variables you could also swap this line: 


```
'url' => 'https://s3-' . getenv('S3_REGION') . '.amazonaws.com/' . getenv('S3_BUCKET') . '/',

**Comment by timkelty** [comment]
@zuccs yep, thats how i currently handle things.

This issue was specifically for the plugin to use the path-based url for the one it automatically generates, just so it works for more cases.
