### ISSUE TITLE
Craft 3.1 project yaml contains S3 credentials

### ISSUE THREAD

**Issue by vanerp** [craftcms/aws-s3#37]
I'm loading the S3 settings via a volumes.php config with references to ENV variables form the .ENV file.  When adding this S3 asset source to Craft 3.1 the AWS credentials are being stored in the project.yaml file. This also puts them into version control and is a potential security issue. 
I know this is related to issue #35, but is there a way to prevent them from being added to the yaml?

**Comment by boboldehampsink** [comment]
Yes, use the #35 version

**Comment by brandonkelly** [comment]
This issue is covered by the [Sensitive Information Could Be Saved in project.yaml](https://docs.craftcms.com/v3/project-config.html#sensitive-information-could-be-saved-in-project-yaml) section in the Project Config docs.
