### ISSUE TITLE
Setting unknown property: craft\awss3\Volume::storageClass on dev-craft-3.1

### ISSUE THREAD

**Issue by acehead** [craftcms/aws-s3#40]
Using Craft 3.1.7, project config enabled and dev-craft-3.1 version of plugin following error occurs when accessing Control panel:
`Setting unknown property: craft\awss3\Volume::storageClass`

**Comment by andris-sevcenko** [comment]
Can you try updating to the just-released 1.1. version of the plugin?

**Comment by acehead** [comment]
Just updated, same issue persists, it seems that https://github.com/craftcms/aws-s3/blob/1.1.0/src/Volume.php is still missing storageClass property

**Comment by andris-sevcenko** [comment]
Right, because it should have been removed by https://github.com/craftcms/aws-s3/blob/master/src/migrations/m180929_165000_remove_storageclass_setting.php

Can you check if your `craft_migrations` table has that migration entry? If it does, what date does it have?

**Comment by andris-sevcenko** [comment]
Can you get a stack trace for that error from the log files?

**Comment by acehead** [comment]
[stacktrace.txt](https://github.com/craftcms/aws-s3/files/2820775/stacktrace.txt)

**Comment by andris-sevcenko** [comment]
> /var/www/config/twig-webpack-extension.php seems to be calling `craft\services\Globals->getSetByHandle('common')`.

I'm not sure that calling Craft functionality from config files is a good idea, as demonstrated by this particular issue. You're invoking Craft before it has a chance to run its migrations and this can lead to unpredictable results. Can you disable that, let the migrations run and see what happens?

**Comment by acehead** [comment]
You're absolutely right, but this was the only way we could make that happen without changing original plugin code.
Commented it out, unfortunately problem is still there, see stacktrace
[stacktrace2.txt](https://github.com/craftcms/aws-s3/files/2820877/stacktrace2.txt)

**Comment by acehead** [comment]
sounds great, waiting for 1.1.1 to be released

**Comment by andris-sevcenko** [comment]
Should be released as of now.

**Comment by acehead** [comment]
Great, worked like a charm, migration was done successfully as well. Thanks for your help!

**Comment by andris-sevcenko** [comment]
I must say, for an instant I was scared when I saw your email :)
