### ISSUE TITLE
Bucket and region can’t be set via environmental settings

### ISSUE THREAD

**Issue by carlcs** [craftcms/aws-s3#42]
It’s recommended to not use volume.php for configuration any longer, and environmental settings should be used instead. https://github.com/craftcms/cms/issues/3655

With this change it’s not possible to set bucket and region to an environment var any longer.

**Comment by brandonkelly** [comment]
We just released v1.2.0, which added the ability to set the Bucket and Region settings to environment variables, directly in the Control Panel.

To do that, change the first dropdown under the Bucket setting from “Choose…” to “Manual…”, and then replace the following text inputs with your environment variable names.

<img width="813" alt="screen shot 2019-02-21 at 4 53 29 pm" src="https://user-images.githubusercontent.com/47792/53212275-3db65880-35f9-11e9-9023-a74fe6667d4b.png">
