### ISSUE TITLE
Bucket dropdown causes issues with certain S3 plugins/add-ons

### ISSUE THREAD

**Issue by makingmemark** [craftcms/aws-s3#45]
The "Bucket" dropdown does not work when using a Heroku add-on such as [Bucketeer](https://elements.heroku.com/addons/bucketeer) as we don't have sufficient privileges to list all buckets in the root.
Having the option to manually type in a bucket name in the UI would resolve this.
Currently we have to hack it by setting up a volume referencing our own S3 bucket and then updating the corresponding volumes row in the database.

**Comment by brandonkelly** [comment]
This is possible as of v1.2.0.
