### ISSUE TITLE
Twig error on all s3 volume's settings pages in CP after Craft 3 migration

### ISSUE THREAD

**Issue by louderthan10** [craftcms/aws-s3#47]
Hi gang. Hitting a Twig bug with this version after migrating from Craft 2. After performing an upgrade, then installing the S3 plugin, when I go to any of my S3 Asset volume's settings pages in the CP, I get the following Twig error:

```
Twig Runtime Error – Twig_Error_Runtime
Key "1" for array with keys "0" does not exist.

    1. in /vendor/craftcms/aws-s3/src/templates/volumeSettings.html at line 125

                                  id: 'expiresAmount',
                    value: expires[0],
                    size: 2,
                    class: 's3-expires-amount'
                }) }}
            </div>
            {{ forms.select({
                id: 'expiresPeriod',
                options: periods,
                value: expires[1],
                class: 's3-expires-period'
            }) }}
        </div>
        {{ forms.hidden({
            name: "expires",
            value: volume.expires,
            class: "expires-combined"
        }) }}
    {% endset %}
```

### Steps to reproduce
1. Deploy updated files/templates/configs for Craft 3
2. Run composer install
3. Perform Craft 3 upgrade (everything works)
4. Enable S3 plugin from Plugins page in CP
5. Click on any S3 volume in the Assets section of the CP (non-S3 volumes load fine)

### Versions
Craft: 2.7.5 - 3.1.14
S3: 1.2.0

**Comment by toyflish** [comment]
I have the same error. There is is a key with wrong expires-date-format migrated to your config/project.yaml

```
volumes:
  [cryptic-volume-id]:
    settings:
      expires: 31days
```
the plugin expects 31days to be seperated by space "31 days"

```
    {% set expires = (volume.expires|length > 0 ? volume.expires|split(' ') : ['', ''])%}
```

after changing project.yaml the new config has to be loaded in the browser. Is there a way to trigger this with the ./craft cli ?

**Comment by andris-sevcenko** [comment]
Not sure how this could have happened, but released 1.2.1 version of this plugin which includes a migration that fixes the corrupted config.

**Comment by jamesmacwhite** [comment]
@andris-sevcenko I've also just experienced this on a Craft 2 to Craft 3 migration. However I am running the 1.2.1 release which has the migration but still get the twig error. In my case my `project.yaml` has `expires: 1months` set for each S3 asset volume currently.

**Comment by louderthan10** [comment]
Seems to work for me now, thanks!

**Comment by andris-sevcenko** [comment]
@jamesmacwhite if you have a pre-update DB backup, I'd love to be able to look at the dump of the `craft_volumes` table. Obviously, redact any and all access keys and other info.

If it's possible, can you send that over to support@craftcms.com and reference this thread?

**Comment by jamesmacwhite** [comment]
@andris-sevcenko Absolutely. I will provide that to you for further investigation.

**Comment by jamesmacwhite** [comment]
@andris-sevcenko Just to confirm. Do you want the DB backup after a Craft 3 migration but before the AWS plugin is installed?

**Comment by andris-sevcenko** [comment]
@jamesmacwhite yup, that would work! If I'll need something else, I'll let you know!

**Comment by jamesmacwhite** [comment]
@andris-sevcenko Understood, I will perform a Craft 2 to 3 migration for this requirement and give you the table data required.

**Comment by jamesmacwhite** [comment]
@andris-sevcenko Just to let you know. I have provided the `craft_volumes` table to support@craftcms.com for further analysis. If you'd like anything else, please let me know. As I am currently working on migrating the existing Craft 2 project, I have plenty of regularly DB backups!

**Comment by louderthan10** [comment]
Just a little update on this after doing a few upgrade dry runs.

If I update from Craft 2 > Craft 3, then enable the plugin at 1.2.1, it still errors.

If I update from Craft 2 > Craft 3, enable the plugin at 1.1.3, then upgrade to 1.2.1, it works.
