### ISSUE TITLE
Dependency between URL and ACL public-read

### ISSUE THREAD

**Issue by kringkaste** [craftcms/aws-s3#48]
We have noticed that when a volume has a URL, the assets in the S3 bucket are automatically set to "public-read" on upload. But this is not wanted in all cases. For example, if you have a restricted Cloudfront distribution. Then the objects in the bucket should not be public and the bucket policy allows access to the objects for the Cloudfront distribution.

It would be helpful if you could overwrite this dependency. A parameter (preferably only in volumes.php) that allows you to set the ACL yourself?

**Comment by cmalven** [comment]
This is affecting a site I'm working on, as well.

**Comment by kringkaste** [comment]
Thank you @phoban01 and @andris-sevcenko  😄I'm looking forward to the next release.

**Comment by andris-sevcenko** [comment]
That was all @phoban01 :)

**Comment by andris-sevcenko** [comment]
1.2.2 is out!
