### ISSUE TITLE
Cache-Control headers - typo

### ISSUE THREAD

**Issue by ostark** [craftcms/aws-s3#5]
IMO this header is called `Cache-Control` not `CacheControl`
https://github.com/craftcms/aws-s3/blob/develop/src/Volume.php#L241

same here:
https://github.com/craftcms/google-cloud/blob/master/src/Volume.php#L205

**Comment by andris-sevcenko** [comment]
Header is indeed called `Cache-Control`, but AWS SDK [expects](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#putobject) `CacheControl`, so this is actually correct.
