### ISSUE TITLE
Add Correct/Ideal IAM settings to documentation

### ISSUE THREAD

**Issue by mzlock** [craftcms/aws-s3#51]
Someone has a pretty good answer for the correct IAM settings for an Assets S3 bucket on the Stack Exchange:
https://craftcms.stackexchange.com/questions/13815/correct-iam-settings-for-amazon-s3-bucket

Might be worth documenting these settings with this plugin?

**Comment by andris-sevcenko** [comment]
That Andris guy sure sounds like he knows what he's talking about!

I'll add updating this to my list of things to do. Also, FTR, the bucket listing permission is not mandatory anymore, if you're specifying the bucket AND region.

**Comment by niemie7** [comment]
@andris-sevcenko - any update on this?  I, too, was looking for a tried and true way to make sure my IAM user is restricted to a single bucket but has only the minimum permissions needed by Craft.

I saw your answer in the link above, tried it out and got this error in IAM/S3 policy review:  

> This policy contains the following error: The following resources are invalid. They must be either '*' or an arn pattern: arn:aws:s3:::
