### ISSUE TITLE
Example of what a configured CloudFront Path Prefix looks like?

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/aws-s3#53]
Hello! Saw that—from #46—you can set the path prefix to allow Craft to invalidate CloudFront assets. Super neat!

Right now I have the distribution ID configured, but it looks like that isn't enough to get Craft to invalidate relevant assets within CloudFront. 

Could you provide an example of what this might look like?

**Comment by andris-sevcenko** [comment]
@aaronbushnell Are you sure they are not invalidated? Keep in mind that the invalidation can take up to 5 minutes per https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-serving-outdated-content-s3/

**Comment by aaronbushnell** [comment]
Ah, thanks, @andris-sevcenko! That very well could be the case. 

Just so I know, what's the use-case for the Path Prefix field? Might need that for a site at some point!

**Comment by andris-sevcenko** [comment]
@aaronbushnell that's covered here: https://github.com/craftcms/aws-s3/pull/46
