### ISSUE TITLE
Setting unknown property: craft\awss3\Volume::urlPrefix

### ISSUE THREAD

**Issue by mdunbavan** [craftcms/aws-s3#54]
Hi,

I have ran into this issue updating a C2 site to craft 3.

Craft version: latest stable
PHP version: 7.2

Here is the volumes table in the db:

![Screenshot 2019-05-01 at 11 02 44](https://user-images.githubusercontent.com/671281/57012933-b42a9480-6c00-11e9-9253-0dbc97813dad.png)

Thanks,
Mark

**Comment by andris-sevcenko** [comment]
What version of the plugin are you using? Is there a stack trace in your log files? If so, can you share that one?

**Comment by mdunbavan** [comment]
@andris-sevcenko I cannot reproduce now but where I went from Craft 2 -3 with this plugin installed it threw the error.

I was running it with the latest plugin version 1.2.2. It was a strange error. So what I did was I downgraded it to 1.1 then I activated the plugin again and ran `craft migrate/all` and when I went back to it everything was fine.

Might be something to try yourself and test it out

**Comment by AbbeyDesign** [comment]
I just got this error trying to upgrade from Craft 2.9.2 to 3.4.29.1. I tried the suggestion above but got the same error. The only way I could get back into the control panel was remove the line completely from the composer.json file and delete the folder  aws in the vendor folder.

**Comment by jmjones88** [comment]
Just got this error too @andris-sevcenko. Migrated Craft 2 to 3 today (3.4.29.1) and installed craftcms/aws-s3 1.2.9. Not really sure what to do as I need aws s3 compatibility. 

Sounds like I need to install the older version first as @mdunbavan suggested, but here's a stack trace to help with debugging, as it appears to still be an issue. Happy to help test anything if needed.

```
2020-07-27 15:03:50 [-][-][-][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: craft\awss3\Volume::urlPrefix in cms/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 cms/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('urlPrefix', 'https://s3.amaz...')
#1 cms/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\awss3\Volume), Array)
#2 cms/vendor/craftcms/aws-s3/src/Volume.php(163): yii\base\BaseObject->__construct(Array)
#3 cms/vendor/craftcms/cms/src/helpers/Component.php(110): craft\awss3\Volume->__construct(Array)
#4 cms/vendor/craftcms/cms/src/services/Volumes.php(521): craft\helpers\Component::createComponent(Array, 'craft\\base\\Volu...')
#5 cms/vendor/craftcms/cms/src/services/Volumes.php(220): craft\services\Volumes->createVolume(Array)
#6 cms/vendor/craftcms/cms/src/services/Volumes.php(234): craft\services\Volumes->getAllVolumes()
#7 cms/vendor/craftcms/cms/src/models/VolumeFolder.php(89): craft\services\Volumes->getVolumeById(3)
#8 cms/vendor/craftcms/cms/src/fields/Assets.php(965): craft\models\VolumeFolder->getVolume()
#9 cms/vendor/craftcms/cms/src/fields/Assets.php(185): craft\fields\Assets->_folderSourceToVolumeSource('folder:dc720e42...')
#10 cms/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\fields\Assets->init()
#11 cms/vendor/craftcms/cms/src/fields/BaseRelationField.php(211): yii\base\BaseObject->__construct(Array)
#12 cms/vendor/craftcms/cms/src/fields/Assets.php(171): craft\fields\BaseRelationField->__construct(Array)
#13 cms/vendor/craftcms/cms/src/helpers/Component.php(110): craft\fields\Assets->__construct(Array)
#14 cms/vendor/craftcms/cms/src/services/Fields.php(553): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#15 cms/vendor/craftcms/cms/src/services/Fields.php(578): craft\services\Fields->createField(Array)
#16 cms/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1942): craft\services\Fields->getAllFields()
#17 cms/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1341): craft\elements\db\ElementQuery->customFields()
#18 cms/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#19 cms/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#20 cms/vendor/yiisoft/yii2/db/Query.php(285): yii\db\Query->createCommand(Object(craft\db\Connection))
#21 cms/vendor/craftcms/cms/src/db/Query.php(168): yii\db\Query->one(NULL)
#22 cms/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1486): craft\db\Query->one(NULL)
#23 cms/vendor/craftcms/cms/src/elements/User.php(403): craft\elements\db\ElementQuery->one()
#24 cms/vendor/yiisoft/yii2/web/User.php(690): craft\elements\User::findIdentity('138')
#25 cms/vendor/craftcms/cms/src/web/User.php(494): yii\web\User->renewAuthStatus()
#26 cms/vendor/yiisoft/yii2/web/User.php(192): craft\web\User->renewAuthStatus()
#27 cms/vendor/craftcms/cms/src/controllers/UsersController.php(234): yii\web\User->getIdentity()
#28 [internal function]: craft\controllers\UsersController->actionSessionInfo()
#29 cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#30 cms/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#31 cms/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('session-info', Array)
#32 cms/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('session-info', Array)
#33 cms/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('users/session-i...', Array)
#34 cms/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('users/session-i...', Array)
#35 cms/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#36 cms/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#37 cms/web/index.php(37): yii\base\Application->run()
#38 {main}
2020-07-27 15:03:50 [-][-][-][info][application] $_GET = [
    'p' => 'admin/actions/users/session-info'
    'dontExtendSession' => '1'
]
```

**Comment by AbbeyDesign** [comment]
Installing an older version did not work for me. I got the same error.

**Comment by jmjones88** [comment]
Same here @AbbeyDesign.. I may try and debug a bit more, but for now I just reverted my install back to craft 2 as I just simply couldn't get this plugin to work.

 I may just ultimately have to remove my asset sources before migration, which feels non-ideal for a migration. If anyone has a workaround that appears to work, please share!

**Comment by olivierbon** [comment]
@jmjones88 This is something we need to address but in the meantime, if you update Craft and the plugin at the same time using the following requirements in your `composer.json`:

```
"require": {
    "craftcms/cms": "^3.4.0",
    "craftcms/aws-s3": "1.1.3",
    "vlucas/phpdotenv": "^3.4.0"
},
```

You shouldn't get any error and will then be able to update the plugin to the latest version from the CP or composer.

**Comment by matthisamoto** [comment]
@olivierbon I am having the same problem on a Craft 2=>3 migration, same error appears.

I've tried removing `vendor`, running `composer install` with these settings in `composer.json` and continue to have the same error.

**Comment by matthisamoto** [comment]
I ended up adjusting the settings JSON within my DB and project config file removing the `urlPrefix` (and `location`) keys, and moved `urlPrefix` to `url`. I also had to update the `expires`, so essentially I was recreating things in the [Install migration](https://github.com/craftcms/aws-s3/blob/7581c658b17212758089c1e2e6c673936b5b2274/src/migrations/Install.php). Not sure why it didn't want to run.

**Comment by aaronbushnell** [comment]
Having the same issue migrating a Craft 2.x site to 3.x, unfortunately.

**Comment by aaronbushnell** [comment]
FWIW I've been able to replicate this issue with a particular site each time I try to do an install of the AWS S3 plugin. Happy to provide any logs/material that helps resolve this one! I tried stepping through things but couldn't _quite_ get a handle on what might be occurring here.

**Comment by aaronbushnell** [comment]
Following up here on my latest test! I tried resaving all of the Asset volumes on the Craft 2 site, exporting that DB and trying the upgrade again. I was hoping a save might alter the Craft 2 database in a way that made the AWS S3 migration run successfully. Unfortunately, no such luck and still getting the same error.

**Comment by aaronbushnell** [comment]
I was able to reduce the test case to a single asset volume like @mdunbavan has in their original comment. Here's the SQL for my volume once I run all of the Craft 2.x to 3.x migrations, but before the AWS plugin install. I've redacted all the keys and URLs:

```sql
INSERT INTO `craft_volumes` (`id`, `name`, `handle`, `type`, `hasUrls`, `url`, `settings`, `sortOrder`, `fieldLayoutId`, `dateCreated`, `dateUpdated`, `dateDeleted`, `uid`) VALUES 
	(1,'Blog','blog','craft\\awss3\\Volume',1,NULL,'{"keyId":"REDACTED_KEY_HERE","secret":"REDACTED_SECRET_HERE","bucket":"REDACTED_BUCKET_NAME","subfolder":"blog","urlPrefix":"https://REDACTED_URL.com","expires":"15days","location":"REDACTED_LOCATION"}',1,1384,'2018-02-03 02:03:56','2020-08-17 13:51:14',NULL,'bf6fe773-9292-4c6d-a81a-2c5e91fa4d53');
```

Here's a screenshot of the volume before the AWS plugin is installed
![Screen Shot 2020-08-17 at 10 06 17 AM](https://user-images.githubusercontent.com/315202/90405137-5fb75c80-e071-11ea-988a-1842b62a2cfc.png)

And as soon as I click the "Install" button I get:

```
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: craft\awss3\Volume::urlPrefix
```

**Comment by marcdebiak** [comment]
We're having the same issue. Haven't been able to move forward with an important update for a few days now.

**Comment by jornwildenbeest** [comment]
Same problem here.

**Comment by andris-sevcenko** [comment]
@aaronbushnell @marcdebiak @jornwildenbeest sorry for the radio silence on this one. Can either of you send over a DB dump where this error is occurring over to support@craftcms.com and reference this issue? Also, if possible, `composer.json` and `composer.lock` files would help tremendously.

**Comment by aaronbushnell** [comment]
That's okay, @andris-sevcenko! I'm sure you all have been busy with releasing 3.5 and immediate bug fixes for stuff people have found thus far.

I've sent my details to the support email, thanks!

**Comment by andris-sevcenko** [comment]
@aaronbushnell got it, thanks!

**Comment by andris-sevcenko** [comment]
Obviously, that was something incredibly stupid. I just cut the 1.2.10 that should resolve this.

If using 1.2.10 still does not work for somebody, can they, please, get in touch over support@craftcms.com with a DB dump and the composer files while referencing this issue?

Thanks for the patience, people!

**Comment by aaronbushnell** [comment]
That worked like a charm, thank you @andris-sevcenko!
