### ISSUE TITLE
Alert error Class 'Aws\Credentials\Credentials' not found

### ISSUE THREAD

**Issue by prahscl** [craftcms/aws-s3#55]
I'm struggling to find any information on this alert error (Class 'Aws\Credentials\Credentials' not found)  I'm getting when trying to "refresh" the Bucket selection dropdown(no buckets are showing).  All credentials for the AWS connection have been tested and they work on local machine.  I'm seeing this error on the offsite development server install of craft v3.1.24.  Thanks for your help.

**Comment by andris-sevcenko** [comment]
What's the installed version of the AWS S3 plugin?

**Comment by prahscl** [comment]
Greetings,

the installed version of aws-s3 is 1.2.2.

**Comment by andris-sevcenko** [comment]
Can you try running `composer update`? Going through the dependencies, the class is required and should be there, but for some reason, it's missing.

**Comment by prahscl** [comment]
Thanks,  found issue.  There was a conflict in the repository being used on Dev site.
