### ISSUE TITLE
Authentication should be able to gracefully handle keys or policies

### ISSUE THREAD

**Issue by Mosnar** [craftcms/aws-s3#56]
Sometimes we need to use an API key locally to authenticate with a bucket; however, upon deploying to our AWS servers, we prefer to use an IAM EC2 policy to authorize the bucket; however, if I set the AWS Key ID setting or AWS Secret setting to an environment variable such as `$AWS_KEY_ID`, which is set locally but not on our staging/production environment, the volume will still try to authenticate with the key.

Ideally, if the environment variable doesn't exist, it should not try to authenticate with a key but rely on the hosts configuration.

**Comment by andris-sevcenko** [comment]
How would the plugin (or Craft, since this would be a precedent) determine whether the value is "$AWS_KEY_ID" or whether that's a missing environment variable? I feel like this could have implications reaching further than the initial issue.

**Comment by Mosnar** [comment]
@andris-sevcenko That's a good point. I agree that it shouldn't be implemented that way. It looks like you can assume roles locally with profiles, that may be a better route, though a bit of a headache to incorporate into our docker environments. I consider this resolved.
