### ISSUE TITLE
S3 log files causing 500 response

### ISSUE THREAD

**Issue by juddlyon** [craftcms/aws-s3#58]
I could not get Craft 3 to index an S3 bucket, despite the same credentials working in Craft 2.

The culprit ended up being thousands S3 log files causing a 500 error, with PHP running out of memory.  I'm not sure if there is a way for the Craft S3 adapter to ignore and short-circuit past gz and txt files, but wanted to open an issue in case there is a simple fix. 

If anybody else has this problem, the fix was to enable a bucket lifecycle rule to retroactively nuke the 500K logfiles, and to disable logging going forward.

**Comment by andris-sevcenko** [comment]
We've had one report with this ever and in that case, the plugin just died trying to fetch the file list from AWS and then trying to figure out what to do with an array of 500K files. So yeah, probably even better to use another bucket for logging.
