### ISSUE TITLE
URLs can be formatted incorrectly for Cloudfront

### ISSUE THREAD

**Issue by Mosnar** [craftcms/aws-s3#63]
Cloudfront has some interesting rules when it comes to URLs. In particular, it requires the following character replacements:
` ` => `%20`
`+` => `%2B`

There's a thread about this here:
https://forums.aws.amazon.com/thread.jspa?threadID=55746

Generally, this isn't really possible to run into in Craft, as Craft handles these characters when you upload directly to the frontend; however, often, we upload massive amounts images directly to S3 and then index them in Craft via the console command.

This means the filenames don't go through Craft's strict sanitation and image URLs can end up 404ing on Cloudfront.

I think it's safe to say AWS is never going to fix this, so it might be worth addressing here.

**Comment by andris-sevcenko** [comment]
I think the best approach here is to build a custom module/plugin that listens to the [relevant event](https://docs.craftcms.com/api/v3/craft-services-assets.html#event-get-asset-url) and just cleans that up.

**Comment by Mosnar** [comment]
@andris-sevcenko Thanks, I agree. After I started digging into it, I realized Volumes don't really have much say over what generated URLs look like.
