### ISSUE TITLE
Consider storing the entire box coordinates of the face

### ISSUE THREAD

**Issue by alexmglover** [craftcms/aws-s3#65]
This would be great for consistently cropping with the same amount of padding around the face. If the coordination of the face were stored, this would be possible.

**Comment by andris-sevcenko** [comment]
This feels a bit out of scope for a plugin that is mainly an adapter to use S3 for file storage. It would probably make sense for you to extend this plugin by overriding the `detectFocalPoint` method on the `Volume` class and then do what you want there.
