### ISSUE TITLE
Base URL is not auto-generated when using "Manual" bucket option

### ISSUE THREAD

**Issue by ldennison-bsd** [craftcms/aws-s3#68]
When using the "Manual" bucket option (i.e. the option that does not require the expansive s3:ListAllMyBuckets permission), the Base URL value is not auto-generated like it is when the bucket is chosen by dropdown. It would seem the only two values necessary to generate the Base URL are the bucket name and the region, in the format: https://s3.[region].amazonaws.com/[bucketname]/

Both of those values are supplied in the manual input process, so the Base URL can still be generated from the manual input. This will improve usability and efficiency when using manual input.

**Comment by andris-sevcenko** [comment]
Great suggestion!

Sorry for the late reaction time - this has been implemented for the next release!
