### ISSUE TITLE
Loss of image quality on upload

### ISSUE THREAD

**Issue by mark-adigital** [craftcms/aws-s3#69]
Hi - we use the [ImageOptim tool](https://imageoptim.com/mac) to compress images before upload, but have found that when then uploading to S3 through Craft there is a noticable drop in quality. Please see below screenshots of the same image uploaded first through Craft and then directly into S3:

<img width="1679" alt="craft-to-s3" src="https://user-images.githubusercontent.com/30312669/64871658-999c0980-d63d-11e9-9633-34d662860a4b.png">

<img width="1679" alt="directly-to-s3" src="https://user-images.githubusercontent.com/30312669/64871666-a15bae00-d63d-11e9-81f5-c74777f6c715.png">

I've tweaked a few Craft config settings to no avail, are you able to advise of a solution? Thanks!

**Comment by andris-sevcenko** [comment]
But we'll add a config setting for people who like living on the edge in Craft 3.4 which allows skipping the file cleansing process. (The image will still be subject to the `rotateImagesOnUploadByExifData` setting, though).

**Comment by benface** [comment]
Related to https://github.com/craftcms/cms/issues/3060

**Comment by andris-sevcenko** [comment]
Closing this as this is a Craft issue, not a plugin issue.
