### ISSUE TITLE
Programmatic way to call the Rekognition focal point detection on images?

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/aws-s3#70]
Is there a way I could trigger a mass focal point detection for images? It looks like it would work if I forced a re-save, but after #60 that no longer appears to be the case. Maybe some kind of CLI action I could run?

**Comment by andris-sevcenko** [comment]
Currently, there's no support for it. Seeing as how that action would incur extra cost, I think it's better left to a custom script/module.
