### ISSUE TITLE
Some images are increased the file size during the uploading progress.

### ISSUE THREAD

**Issue by P233** [craftcms/aws-s3#71]
When I was using this plugin to upload images to S3, I noticed some PNG files were increased the file size. For example, a PNG file is 194.7KB on my local computer, and the file size is 482.7KB in S3 after uploading. But if I directly upload this file through the S3 web page, the file size won't increase.

Could you try this image: https://people.sc.fsu.edu/~jburkardt/data/png/bell_v22.png, I searched it from google and confirmed it will be increased the file size.

Craft version `3.3.15`
aws-s3 version `1.2.5` with the default configuration

**Comment by angrybrad** [comment]
You're likely experiencing this issue: https://craftcms.stackexchange.com/a/16777/57
