### ISSUE TITLE
Add Environment variable names in README.md

### ISSUE THREAD

**Issue by shide1989** [craftcms/aws-s3#72]
HI,

that would be great and save us time if you could add the environment variables to pass to your plugin. Right now we have to dig in the S3/Cldoufront documentation to search for it, and i'm not even sure what they are exactly and what the options

Thanks !

**Comment by andris-sevcenko** [comment]
The environment variables are whatever you set in your `.env` file and you can use those values later when setting up the volume. On top of the [default Volume settings](https://docs.craftcms.com/v3/config/environments.html#control-panel-settings),  this plugin allows [some other Volume settings](https://github.com/craftcms/aws-s3/blob/master/CHANGELOG.md#added-2) to be set to environment variable, too.

Unless I'm totally misunderstanding what you mean with your issue :)

**Comment by shide1989** [comment]
Hi, thanks I understood that, I was talking about their names.
If you could give the names to define like `AWS_PROFILE` or `AWS_ACCESS_KEY_ID` etc.. that would be very helpful

**Comment by andris-sevcenko** [comment]
The names are whatever you want them to be since you pick the name in the `.env` file and then use the variable name in the Volume settings.

**Comment by shide1989** [comment]
Actualy, my point is that it's not what i want them to be, because AWS SDKs uses standard environment var names, like i mentionned above.
if you could provide them for S3/Cloudfront that would save us the time to look for them in the AWS documentation :)

**Comment by andris-sevcenko** [comment]
But the point here is to configure the Volume and let it deal with the AWS SDK, no? I mean, for all you know, we might swap out AWS SDK to a custom-built solution sometime. Well, we're using [Flysystem](https://flysystem.thephpleague.com/docs/) under the hood and we don't interact with AWS SDK directly, so, looking strictly from the plugin's view - it doesn't even know about AWS SDK.

You should just tell the AWS S3 Volume what keys it should be using and let it worry about what it does with that information.

And it's entirely possible that I'm still missing your point entirely - please feel free to call me names and just explain it once again if that's the case :)
