### ISSUE TITLE
Cloudfront Invalidation performance and rate limit issues

### ISSUE THREAD

**Issue by dreadfullyposh** [craftcms/aws-s3#73]
We have a site that is using S3 and Cloudfront alongside ImageOptimize with quite a few image transforms being generated.

When we go to set a focal point, the page just hangs on save and eventually the AJAX request times out after 30 seconds.

From our investigation it seems like this is related to the Cloudfront invalidations being performed synchronously, ie making rapid fire invalidation requests, one per file.

It seems like these should be sent off to the queue so they don't block the server up and cause the AJAX request to fail. 

Do you have any suggestions here?

As a follow-on to the, it appears the number of invalidations also hits the rate limit for Cloudfront, so it might be wise for the method sending the invalidation to look for the rate limit response and try again later.

**Comment by dreadfullyposh** [comment]
Ping on this.

**Comment by andris-sevcenko** [comment]
Hmm. Okay. One way of dealing with this would be, indeed, batching the invalidated files. So if a file has 20 transforms, this doesn't create 20 requests.

Out of curiosity, how many transforms are we talking about here?

**Comment by dreadfullyposh** [comment]
It looks like currently I knocked it down to 6 to prevent this from being an issue, but previously it was something like 20. 

We're using ImageOptimize on this site, which then stores its transformations using Craft's native asset saving methods. So it adds up quickly if you're using 3-4 variants at 1x, 2x, and 3x, etc.

Obviously this particular issue is caused by the plugin generating so many transforms, but since it falls back to native Craft (and it could potentially happen with native Craft transforms) it seems like it should probably be addressed in the core.

**Comment by andris-sevcenko** [comment]
I'll try to get to this over the course of this week.

**Comment by dreadfullyposh** [comment]
Any progress on this?

**Comment by andris-sevcenko** [comment]
Sorry, @dreadfullyposh, got a little busy with other stuff. This is still on my radar, though, but can't promise I'll get to it before next week.

**Comment by kylecotter** [comment]
Hi! Not to be a pest, but any update on this? It's biting us on a couple projects. Thanks, Andris!

**Comment by andris-sevcenko** [comment]
@kylecotter I haven't had the opportunity to work on this yet, however it is still on my list :)

**Comment by lenvanessen** [comment]
Just giving this a small nudge. We're also experiencing issues with this on some projects

**Comment by andris-sevcenko** [comment]
Good news! I'm going have a go at it this week!

**Comment by andris-sevcenko** [comment]
Alright, so any invalidations are now batched per request, so if you modify a file that invalidates 20 transforms, that should get executed as one invalidation request.

Some other issues are still there, such as hitting the rate limit of the API, but those really should be separated out to their own issues.
