### ISSUE TITLE
Namespacing issue? Call to undefined function Aws\boolean_value() in Configuration.php

### ISSUE THREAD

**Issue by BrewCurious** [craftcms/aws-s3#74]
I'm running a Craft site that the client recently updated all core CMS and plugins for. The updates all seemed to have completed without issue and all frontend functionality appears normal. The only issue is that there are now multiple places within the administrative site that S3-stored assets are generating the above error message.

This problem is only happening in production environments for me, so I'm wondering about case-sensitivity-related issues or similarly environment-dependent possibilities.

The three places that I know are receiving that error message are:
- [Admin: /settings/assets/volumes/1] Refreshing the dropdown menu of AWS S3 buckets
- [Admin: /assets] Uploading new files to an S3 asset store or renaming existing S3 assets
- [Admin: /entries/...] Uploading new files to any WYSIWYG editor or direct asset field using an S3 asset store within any entry

The code generating this particular error originates from:
- /vendor/aws/aws-sdk-php/src/S3/UseArnRegion/Configuration.php (line 13)
```
namespace Aws\S3\UseArnRegion;
use Aws;

...

$this->useArnRegion = Aws\boolean_value($useArnRegion);
```

The intended reference for the boolean_value function comes from:
- /vendor/aws/aws-sdk-php/src/functions.php

Production environment basics:

- AWS Amazon Linux (Linux 4.14.152-98.182.amzn1.x86_64)
- PHP 7.2.24
- MySQL 5.7.22
- Craft Pro 3.3.17
- Amazon S3 1.2.5

**Comment by khalwat** [comment]
The code in question is here:

```php
    public function __construct($useArnRegion)
    {
        $this->useArnRegion = Aws\boolean_value($useArnRegion);
        if (is_null($this->useArnRegion)) {
            throw new ConfigurationException("'use_arn_region' config option"
                . " must be a boolean value.");
        }
    }
```

Which looks fine and is properly namespaced. I'd be tempted to nuke composer and reinstall everything to make sure you're using the latest everything, and your Composer autoload files are properly generated.

**Comment by BrianBravo** [comment]
I've ran the commands without success.

**Comment by BrianBravo** [comment]
I tried setting up a new volume and I received the same error message. 

![image](https://user-images.githubusercontent.com/1137099/70931373-e86e8c00-1ffc-11ea-8366-960cefb2ccfc.png)

**Comment by angrybrad** [comment]
Any chance we could get some Craft CP and SSH access to a box this is happening on?  If so, could you send over to support@craftcms.com?

**Comment by BrianBravo** [comment]
You bet!

**Comment by angrybrad** [comment]
@BrianBravo It looks like you've got a CloudFront distribution in front of the site, but it's also covering Control Panel requests.  You'll want to exclude _all_ CP requests (GET and POST) from CF (or any other CDN) because you'll get weird issues like this.

Plus there's no real reason to have the CP behind a CDN.

@BrewCurious not sure if you're working with @BrianBravo, but if not, guessing it's a similar issue for you as well?

**Comment by kieraneglin** [comment]
I am seeing this issue as well.  Was a resolution ever found?

**Comment by kayqq** [comment]
I just started getting this issue as well.

**Comment by BrewCurious** [comment]
@angrybrad While I'm not working with @BrianBravo, it does sound as though we were running into the same issue. The problem was resolved in my project by adding Cloudfront behaviors to remove caching to index.php and /admin/* routes.

**Comment by Juberstine** [comment]
I work for Media Temple and if you are a Media Temple AWS Cloud Hosting customer, please contact our support team to discuss the solution to this problem, as we are aware of a specific configuration on our AWS hosting relate to this. Feel free to reference my name when contacting support.

**Comment by niraj-shah** [comment]
I was getting this issue in Laravel 5 today, after updating my app libraries using composer. I managed to fix it by clearing the app cache using `php artisan cache:clear`.
