### ISSUE TITLE
CP asset downloads broken

### ISSUE THREAD

**Issue by gijsstegehuis** [craftcms/aws-s3#77]
Release 1.2.6 broke CP asset downloads. 
I am getting several `Could not open create the stream for [x]` errors, where as on 1.2.5. this wouldn't happen.

**Comment by andris-sevcenko** [comment]
Uh, OK. Looking into this now.

**Comment by andris-sevcenko** [comment]
Are you using an AWS S3 bucket or some storage that pretends to be one? Is this somewhere where it's possible to access CP and FTP? I'm getting an error, but a different one and I'll look into solving that one.

**Comment by andris-sevcenko** [comment]
You know what, never mind. It seems that the streaming change is not compatible with how Yii sends files, anyway, so I'll just revert it.

**Comment by gijsstegehuis** [comment]
Allright. thanks!

**Comment by andris-sevcenko** [comment]
Done!
