### ISSUE TITLE
Removing subfolder path looks to have deleted our S3 files

### ISSUE THREAD

**Issue by johnj24** [craftcms/aws-s3#79]
I'm not sure if I made a huge mistake or if this can be remedied, but I removed the "Subfolder path" from the Volume settings in Craft and the contents of that S3 subfolder are entirely gone from that subfolder in our S3 bucket. Any idea what exactly could have gone wrong here and if its at all possible to restore a bucket on S3?

Thanks.

**Comment by johnj24** [comment]
After looking into the issue I've found the reason files are missing. It wasn't due to a subfolder path being deleted.

**Comment by andris-sevcenko** [comment]
No problem, glad you found the cause!
