### ISSUE TITLE
Config for S3 credentials and bucket

### ISSUE THREAD

**Issue by mikefrancis** [craftcms/aws-s3#8]
It would be great if there was the option to store the AWS ID, secret and bucket name in a config file (so it could be made with environment variables) to make this plugin more [12 factor](https://12factor.net)-y.

**Comment by andris-sevcenko** [comment]
Already possible with https://github.com/craftcms/docs/blob/master/en/configuration.md#overriding-volume-settings.

You're looking for `keyId`, `secret` and `bucket` key names.

**Comment by mikefrancis** [comment]
Ah-ha! That's awesome, thanks. Is this the same for Craft 2.0 too?

**Comment by brandonkelly** [comment]
No, that’s a new feature. Craft 2 doesn’t make it possible to override asset source settings from PHP.

**Comment by mikefrancis** [comment]
Also would it be worth documenting this?

**Comment by brandonkelly** [comment]
Probably :)

**Comment by mikefrancis** [comment]
I'm trying to set this up - when I hit save I get:

```Couldn’t save volume.```

I see the `keyId`, `secret` and `bucket` get copied into the form but it just won't save.

There's no validation errors from what I can see, not sure what the issue is?

**Comment by brandonkelly** [comment]
The Region field is also required. Have you set that in the UI?

**Comment by mikefrancis** [comment]
I can't see a region field 😕  unless I'm going mad?

![screenshot](https://user-images.githubusercontent.com/1672610/30542866-d5e6bdbe-9c78-11e7-8434-0bb941b3f020.png)

**Comment by mikefrancis** [comment]
If I add the `region` key to it the `config/volumes.php`, it works 🎉 

Once I've finished this project I'll try and do a PR for documenting this.

**Comment by lafeer** [comment]
How can you setup all volume handles of volume type Amazon S3, to use the same credentials ( url, keyId, secret, bucket, region) without having to copy paste each time a new S3 volume is added?

**Comment by andris-sevcenko** [comment]
Just have an array of the handles at the top of the config file and generate the returned config array with a `foreach` loop.

**Comment by wfendler** [comment]
@andris-sevcenko - i was just about to try this. is there a way to dynamically pull all the s3 volumes without needing to maintain an array of them manually in `volumes.php`?

**Comment by andris-sevcenko** [comment]
@wfendler sorry, no, but we're working on Craft upgrades that would make this a little easier.

**Comment by tomasbreffitt** [comment]
Is it possible to prevent the keyID and secret from being stored in the database? I know they should be safe in the database, but I'd rather them only reside in my env file.

**Comment by brandonkelly** [comment]
@tomasbreffitt Sorry not currently.
