### ISSUE TITLE
Unable to serve URLs with cloudfront origin path

### ISSUE THREAD

**Issue by timkelty** [craftcms/aws-s3#83]
Here's what I'm trying to set up:

- A single s3 bucket, with my assets living in env-specific directories, e.g.
  - `my-bucket/production/public`
  - `my-bucket/staging/public`
- For each env, Cloudfront distribution, with the origin path set to `/[environment]/public`
- This results in a bucket object, eg: `staging/public/fpo/500x500.png`, with a public URL of `https://d3lrzmrgqsok6q.cloudfront.net/fpo/500x500.png`

This seems like a fairly basic AWS setup, but AFAIK, there is no way to set this up in a Craft volume.

The problem is the **subfolder** asset option is always included in the URL, when in this case it shouldn't be. E.g., if I set the **subfolder** to `staging/public/fpo`, the URLs will be `https://d3lrzmrgqsok6q.cloudfront.net/staging/public/fpo/500x500.png`, which is not correct.

I tried setting the **Cloudfront Path Prefix** to `fpo`, but it doesn't appear to affect the URL.

### Possible solutions

- If **Cloudfront Path Prefix** is set, use it (and only it) as the path prefix for the asset when generating the URL
- Introduce a new boolean option, **Include subfolder in URL?**
  - In my case, I would set this to false, and simply set the Base URL for the volume to `https://d3lrzmrgqsok6q.cloudfront.net/fpo/`

Related: https://github.com/craftcms/aws-s3/pull/46
/cc @samstevens 

![Screen_Shot_2020-03-30_at_11_16_56_AM-2](https://user-images.githubusercontent.com/18329/77929934-3c357600-7278-11ea-801a-7f0db05511e6.jpg)

**Comment by andris-sevcenko** [comment]
The (1) might be a breaking change for people using that setting _and_ the subfolder setting, so that's probably not going to happen.

I'd definitely be willing to entertain a PR for (2), though!

**Comment by timkelty** [comment]
I believe this is covered by https://github.com/craftcms/aws-s3/pull/78
