### ISSUE TITLE
Php error in log file

### ISSUE THREAD

**Issue by wihodges** [craftcms/aws-s3#84]
So this isn't really causing any noticeable issue, but I have noticed the same error across several installations that in the phperrors.log. and on one particular site that has heavy volume the phperrors.log has ballooned to 2.7g with same error over and over again.

Error is:

[06-May-2020 16:32:05 America/Chicago] PHP Warning:  is_readable(): open_basedir restriction in effect. File(/home/USER/.aws/config) is not within the allowed path(s): (/home/USER/WEBPATH:/var/lib/php/session:/tmp) in /home/USER/WEBPATH/vendor/aws/aws-sdk-php/src/S3/UseArnRegion/ConfigurationProvider.php on line 131

**Comment by andris-sevcenko** [comment]
Can you try setting the env variable `AWS_CSM_ENABLED` to false? (https://github.com/aws/aws-sdk-php/issues/1659#issuecomment-440241075)

**Comment by angrybrad** [comment]
Looks like you're storing some AWS credentials in `/home/USER/.aws/config`. You'll want to modify your php.ini file's `open_basedir` to include that path so PHP can access it.

**Comment by wihodges** [comment]
I'm not storing anything there, I set up S3 assets like everyone else in settings/assets configuration panel.

**Comment by angrybrad** [comment]
@wihodges Does [Andris'](https://github.com/craftcms/aws-s3/issues/84#issuecomment-625077254) suggestion work?

**Comment by wihodges** [comment]
@angrybrad sorry for delayed response. 

I tried adding putenv('AWS_CSM_ENABLED=false'); to config/general.php and also tried AWS_CSM_ENABLED="false" in .env file. Not sure if this was correct placement, but neither changes had any effect, as phperrors.log continues with the logging.

Beyond the curious php warning, the biggest issue I have now is that the phperrors.log file has ballooned into a 10gb file. I obviously have deleted it to restart the log but seems like it should limit itself to 10mbs per file and 5 total in rotation.

**Comment by wihodges** [comment]
So I was digging around some of my sites, I noticed that this only happens to the sites that I have defined a Cloudfront distribution ID to. When it's just the S3 bucket, no errors being logged.
