### ISSUE TITLE
Switching off "Add the subfolder to the Base URL" on an existing site?

### ISSUE THREAD

**Issue by andreimoment** [craftcms/aws-s3#88]
I have a site using Amazon S3 for *email* assets. URL changes for images referenced in already sent emails would break the emails.

What will be the effect of switching off "Add the subfolder to the Base URL" ? 

Will existing assets be influenced in any way or would *only* new assets be uploaded to the general bucket space instead into subfolders?

Basically, is it safe to make this switch on an existing site where I'd like to avoid changes of existing image URLs?

**Comment by andris-sevcenko** [comment]
> Will existing assets be influenced in any way or would only new assets be uploaded to the general bucket space instead into subfolders?

This setting only changes how the URL is generated, not where the Asset is uploaded, so any URLs already out there in the wild (or, well, in emails already sent) would not be affected.

The use case for which this setting was added is covered in https://github.com/craftcms/aws-s3/pull/78, so maybe that will add some clarity for you.

Just curious - what are you trying to accomplish?

**Comment by andreimoment** [comment]
Thank you for responding... maybe you can provide insight for the scenario
I'm facing...

> What are you trying to accomplish

My client is using CraftCMS for as an email builder. A team of 10+ creates
emails which are then run through a rails-based premailer app and
distributed via a marketing platform.

There are a number of email entry types, each with their image assets in an
appropriate place. Some emails reuse assets from others, so naming and
organization is important.

We started with image assets for marketing emails in

assets > images > marketing-emails > 2020

but that quickly got un-yieldy. So, we introduced 2020 > month, as in 2020
> 1, 2020 > 2, 2020 > 3 etc. "current month" sub-folders.

But, we still have a lot of images in the 2020 folder, because for some
time we didn't have the month subfolders.

The images in assets > images > marketing-emails > 2020 have already been
sent. If the images urls change, these images will no longer load in the
already distributed recipients' emails. So, changing the links to the
images on AWS is not acceptable.

Here's where the tension lies. I'd like to clean up the "assets > images >
marketing-emails > 2020" folder and move images to "assets > images >
marketing-emails > 2020 > month" subfolders.

Is it possible to move all these assets AND preserve the AWS links? When I
tested this (before the release of the latest version of the plugin), the
AWS URLs changed, so that was a no-go.

Ideas?

**Comment by andris-sevcenko** [comment]
So you're asking if you can have the files in both places? I don't think that's possible unless you copy the files to both places.

There are ways to accomplish that with some [advanced S3 redirects](https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html#advanced-conditional-redirects), but it's a bit out of my area of expertise.
