### ISSUE TITLE
Cloudfront invalidation

### ISSUE THREAD

**Issue by umkasanki** [craftcms/aws-s3#89]
Hi guys.
I use S3 volumes with cloudfront caching. 
Is it possible automatically send cloudfront invalidation after manipulating with images?
Now I should do it manualy after each cropping/flip/etc...

Screen record: https://youtu.be/bloy4nwNKxk

Volume settings:
![изображение](https://user-images.githubusercontent.com/496132/85111608-3dde5c80-b21d-11ea-976c-3c050909dc5e.png)

Imagick 3.4.4 
Craft Solo 3.4.22.1
Amazon S3: 1.2.8

_
Thanks

**Comment by andris-sevcenko** [comment]
Invalidations are created automatically if you've provided the CF Distribution ID.

If you'll check the [video at 2:01](https://youtu.be/bloy4nwNKxk?t=61), you'll see there are two invalidations already running (one for each time you re-saved the image) - they just aren't finished yet.

**Comment by umkasanki** [comment]
thanks
