### ISSUE TITLE
Missing s3 metadata attribute; Cache-Control headers

### ISSUE THREAD

**Issue by michaeljoy** [craftcms/aws-s3#91]
The ability to set Cache-Control metadata on all files uploaded and or modified on S3 asset volumes is a must for proper caching. Otherwise the browser never gets the correct data. AWS Cloudfront doesn't set this and relies on the origin, which if it's S3, the header data needs to be in the meta-data of the file.

Simply adding this after the fact is not maintainable when non-technical, marketing type users are in charge of content.

Cache-Control: max-age=31536000

Cache invalidation would be an awesome future feature, but at minimum being able to set it at all by default would be nice, even if it requires a config file change.

**Comment by andris-sevcenko** [comment]
Have you looked into using the "Cache Duration" AWS S3 volume setting? That's exactly what it does.

<img width="533" alt="Screen Shot 2020-07-01 at 08 06 41" src="https://user-images.githubusercontent.com/1891118/86205135-cfc95c00-bb71-11ea-8438-649f40cde8e9.png">
