### ISSUE TITLE
Cloudfront cache not invalidated on asset replacement

### ISSUE THREAD

**Issue by brianjhanson** [craftcms/aws-s3#98]
### Description
We've been having an issue where a client would like to replace assets from Craft but not have the file paths change. We've gotten several bug reports of the assets updated this way not updating and have eventually tracked it down to the Cloudfront cache not being invalidated. 

### Steps to reproduce

1. Upload an asset to a volume with S3 and Cloudfront configured
2. View the asset via the Cloudfront URL
3. Replace the asset from within Craft
4. View the asset URL again. The asset will be the original and not the updated version

### Additional info

<table class="data fullwidth fixed-layout" dir="ltr">
        <tbody>
                            <tr>
                    <th class="light">PHP version</th>
                    <td>7.2.33</td>
                </tr>
                            <tr>
                    <th class="light">OS version</th>
                    <td>Linux 4.9.0-12-amd64</td>
                </tr>
                            <tr>
                    <th class="light">Database driver &amp; version</th>
                    <td>MySQL 5.5.5</td>
                </tr>
                            <tr>
                    <th class="light">Image driver &amp; version</th>
                    <td>Imagick 3.4.4 (ImageMagick 6.9.7-4)</td>
                </tr>
                            <tr>
                    <th class="light">Craft edition &amp; version</th>
                    <td>Craft Pro 3.5.10.1</td>
                </tr>
                            <tr>
                    <th class="light">Yii version</th>
                    <td>2.0.38</td>
                </tr>
                            <tr>
                    <th class="light">Twig version</th>
                    <td>2.12.5</td>
                </tr>
                            <tr>
                    <th class="light">Guzzle version</th>
                    <td>6.5.5</td>
                </tr>
                            <tr>
                    <th class="light">Imagine version</th>
                    <td>1.2.3-dev</td>
                </tr>
                    </tbody>
    </table>

<table class="data fullwidth fixed-layout" dir="ltr">
            <tbody>
                                    <tr>
                        <th class="light">Amazon S3</th>
                        <td>1.2.11</td>
                    </tr>
                                    <tr>
                        <th class="light">Asset Rev</th>
                        <td>6.0.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Blitz</th>
                        <td>3.6.8</td>
                    </tr>
                                    <tr>
                        <th class="light">Bulk Edit</th>
                        <td>2.0.5</td>
                    </tr>
                                    <tr>
                        <th class="light">Expanded Singles</th>
                        <td>1.1.3</td>
                    </tr>
                                    <tr>
                        <th class="light">Feed Me</th>
                        <td>4.2.3</td>
                    </tr>
                                    <tr>
                        <th class="light">Freeform</th>
                        <td>3.8.1</td>
                    </tr>
                                    <tr>
                        <th class="light">ImageOptimize</th>
                        <td>1.6.16</td>
                    </tr>
                                    <tr>
                        <th class="light">Linkit</th>
                        <td>1.1.11</td>
                    </tr>
                                    <tr>
                        <th class="light">Neo</th>
                        <td>2.8.8</td>
                    </tr>
                                    <tr>
                        <th class="light">OneCookieConsent</th>
                        <td>1.0.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Redactor</th>
                        <td>2.7.4</td>
                    </tr>
                                    <tr>
                        <th class="light">Retour</th>
                        <td>3.1.41</td>
                    </tr>
                                    <tr>
                        <th class="light">SEOmatic</th>
                        <td>3.3.18</td>
                    </tr>
                                    <tr>
                        <th class="light">Typogrify</th>
                        <td>1.1.18</td>
                    </tr>
                            </tbody>
        </table>

**Comment by andris-sevcenko** [comment]
Did you verify in the AWS console that there was no invalidation job created? The invalidation is not instant on AWS.

**Comment by brianjhanson** [comment]
Nope, doesn't look like an invalidation job gets created in Cloudfront

**Comment by andris-sevcenko** [comment]
Hmm. Have you set the `CloudFront Distribution ID` setting correctly in volume settings?

**Comment by brianjhanson** [comment]
We have and have triple checked it. My original guess at the issue was that `EVENT_AFTER_SAVE` didn't run when replacing an asset but then I realized that maybe I just wasn't actually saving the asset after replacing it. But alas, even when I made sure to click "save" I didn't see a new invalidation created. Would there be any logs around this I could look at to give you better clues? It's happening on a production environment and we only replace the assets about once a month, so I haven't had a chance to step through the code and narrow it down yet.

**Comment by andris-sevcenko** [comment]
Hmm, I just checked locally with the AWS plugin version 1.2.11 and it creates an invalidation as expected.

You can probably try by uploading a test asset and replacing it to test around it - there are no specific logs about this, no.

**Comment by brianjhanson** [comment]
I'm pretty sure this is / was related to us having an incorrect setting for the Cloufront subfolder. I haven't had a chance to give you a good test case so I'm going to close this for now. If I run into it again (and can give you a good test case) I'll re-open. 

Thanks!
