### ISSUE TITLE
Unable to upload file: Getting unknown property: craft\\awss3\\Volume::path

### ISSUE THREAD

**Issue by Chris7Ford** [craftcms/aws-s3#99]
I am trying to create an asset and upload a file programmatically via PHP to allow user file upload.  My code worked with local volumes, but since installing this plugin and changing the volume to an S3 bucket, I am unable to upload.

Here is the code that uploads the file:

```
public function uploadNewAsset(UploadedFile $uploadedFile, $folderId) {
      $ret = array(
        "success" => false
      );
      if (empty($folderId)) {
        $ret['message'] = 'No target destination provided for uploading';
        return $ret;
      }
      if ($uploadedFile->getHasError()) {
        $ret['message'] = 'Error uploading file: ' . $uploadedFile->error;
        return $ret;
      }
      // Move the uploaded file to the temp folder
      if (($tempPath = $uploadedFile->saveAsTempFile()) === false) {
        $ret['message'] = 'Error uploading file: ' . UPLOAD_ERR_CANT_WRITE;
        return $ret;
      }
      $assets = Craft::$app->getAssets();
      $folder = $assets->findFolder(['id' => $folderId]);
      // Check the permissions to upload in the resolved folder.
      //$filename = Assets::prepareAssetName($uploadedFile->name);
      $asset = new Asset();
      $asset->tempFilePath = $tempPath;
      $asset->filename = $uploadedFile->name;
      $asset->newFolderId = $folder->id;
      $asset->volumeId = $folder->volumeId;
      $asset->avoidFilenameConflicts = true;
      $asset->setScenario(Asset::SCENARIO_CREATE);
      $asset->uploaderId = \Craft::$app->getUser()->getId();
      $result = Craft::$app->getElements()->saveElement($asset);
      if (!$result) {
        $ret['message'] = 'Error Saving Asset';
        return $ret;
      }
      $ret['success'] = true;
      $ret['asset'] = $asset;
      return $ret;
    }
```

The error occurs at this line: `$result = Craft::$app->getElements()->saveElement($asset);` when the asset is saved:
`Getting unknown property: craft\\awss3\\Volume::path`

I don't see any documentation on how this would be done. Is this a bug? Or can you tell me how a file should be uploaded to the bucket while creating an asset? Thanks!

**Comment by andris-sevcenko** [comment]
Can you, please, post the full stack trace from your log files leading up to the error?

**Comment by Chris7Ford** [comment]
Hi @andris-sevcenko, thanks for getting back to me.  Unfortunately, I no longer have the stack trace for this error, but for anyone else that may come across it, I resolved this by deleting the volume and creating it again. I was able to upload files without any problems then.

Thank you!
